services:
  strapi:
    build: .
    container_name: strapi_app

    ports:
      - "1337:1337"

    volumes:
      - ./app:/app
      - /app/node_modules
      - ./backup:/backup
    
    environment:
      - NODE_ENV=development

    restart: unless-stopped